spring.application.name=taskmanager-pi


# <======== MongoDB Atlas ========>:
    # MongoDB connection
    spring.data.mongodb.uri=${MONGODB_URI}

    # Server configuration.
    server.port = 8080

    # Logs configuration.
    logging.level.org.springframework.data.mongodb = DEBUG
    logging.level.org.mongodb.driver = INFO